export const POSTS = [
	{
		_id: "1",
		text: "Let's build a fullstack MERN",
		img: "/posts/post3.png",
		user: {
			username: "sanjeevan",
			profileImg: "/avatars/boy1.png",
			fullName: "sathiya sanjee",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Project",
				user: {
					username: "sangavi",
					profileImg: "/avatars/girl1.png",
					fullName: "sathiya sangavi",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "2",
		text: "How you guys doing? 😊",
		user: {
			username: "sanga",
			profileImg: "/avatars/boy2.png",
			fullName: "sanga",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "sans",
					profileImg: "/avatars/girl2.png",
					fullName: "sans",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "3",
		text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
		img: "/posts/post2.png",
		user: {
			username: "Sarmi",
			profileImg: "/avatars/boy3.png",
			fullName: "Sarmi",
		},
		comments: [],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894", "6658s895", "6658s896"],
	},
	{
		_id: "4",
		text: "I'm learning GO this week. Any tips? 🤔",
		img: "/posts/post3.png",
		user: {
			username: "Sarmi",
			profileImg: "/avatars/boy3.png",
			fullName: "Sarmi",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "visakan",
					profileImg: "/avatars/girl3.png",
					fullName: "visakan",
				},
			},
		],
		likes: [
			"6658s891",
			"6658s892",
			"6658s893",
			"6658s894",
			"6658s895",
			"6658s896",
			"6658s897",
			"6658s898",
			"6658s899",
		],
	},
];

export const USERS_FOR_RIGHT_PANEL = [
	{
		_id: "1",
		fullName: "siva vithu",
		username: "visakan",
		profileImg: "/avatars/boy2.png",
	},
	{
		_id: "2",
		fullName: "sivanesan Sarmi",
		username: "saisarmi",
		profileImg: "/avatars/boy3.png",
	},
	{
		_id: "3",
		fullName: "Sathiya sangavi",
		username: "sangavi",
		profileImg: "/avatars/girl1.png",
	},
	{
		_id: "4",
		fullName: "Sathiya sansayan",
		username: "sansayan",
		profileImg: "/avatars/boy2.png",
	},
];